name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.x'
          cache: 'composer'
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Lint
        run: vendor/bin/phpcs
      - name: Test
        run: vendor/bin/phpunit
